# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Potatech
name: Kent
email: jpang9@outlook.com
description: >-
  The names Kent, I'm a cybersecurity enthusiast with the goal of learning as much as I can within this industry. <br>
  Focused on Tryhackme for about 8 months, alot less now as I'm more occupied with writing code and analysing malware. <br>
  There's some notes below regarding my hunting journey, and if you find something wrong, feel free to shoot me an email aye.


baseurl: "" # the subpath of your site, e.g. /blog
url: "https://go-outside.xyz" # the base hostname & protocol for your site, e.g. http://example.com

notes_link: "#"
github_link:  https://github.com/Jpang9
linkedin_link: https://www.linkedin.com/in/kent-pang-1425bb239/
tryhackme_link: "https://tryhackme.com/p/Jpang9"

# Uncomment as necessary
work:
    # Item name, Item URL
  - ["TCM Malware Analysis (PDF)", /Filesfolder/certificate-of-completion-for-practical-malware-analysis-triage.pdf]
#  - ["MalJupyter", https://github.com/Jpang9/MalJupyter] Keep hidden as it breaks the website lmao
#  - ["Name of work", https://URLTOWORK.com]


# Build settings
plugins:
  - jekyll-feed

sass:
  style: compressed