# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Potatech
name: Kent
email: jpang9@outlook.com
description: >-
  The names Kent, I'm a cybersecurity enthusiast, don't really care what I'm learning as long as I'm learning something.
  Currently busy with Malware Analysis and Malware Development, but hey
  these are my notes so feel free to go through it if you want :P. 
  
  (PS, Did I write or record information that's wrong or invalid? Shoot me an email about
  the error, and I'll look into it, or you could just email me calling me a d**k head too, kinda rude, but I don't care :D.)

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://go-outside.xyz" # the base hostname & protocol for your site, e.g. http://example.com

notes_link: "#"
github_link:  https://github.com/Jpang9
linkedin_link: https://www.linkedin.com/in/kent-pang-1425bb239/
tryhackme_link: "#"

# Uncomment as necessary
work:
  - ["TCM Malware Analysis (PDF)", /Filesfolder/certificate-of-completion-for-practical-malware-analysis-triage.pdf]
#  - ["Name of work", https://URLTOWORK.com]
#  - ["Name of work", https://URLTOWORK.com]


# Build settings
plugins:
  - jekyll-feed

sass:
  style: compressed